# ============= APPLICATION BASIC SETTINGS =============
spring.application.name=philharmonic

# ============= DATABASE SETTINGS (PostgreSQL) =============
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/philharmonic-db
spring.datasource.username=postgres
spring.datasource.password=osdfinale

# ============= JPA/HIBERNATE SETTINGS =============
# ??????????? update ??? ??????????, validate ??? ??????????
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

# ????????? SQL ?????????????, ??? ??? ?????????? Init.java
spring.sql.init.mode=never

# ============= DEFAULT PASSWORD (??? Init.java) =============
app.default.password=admin123

# ============= LOGGING SETTINGS =============
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ============= REDIS CACHE SETTINGS =============
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# ============= SERVER SETTINGS =============
server.error.include-message=always
server.error.include-binding-errors=always
spring.mvc.hiddenmethod.filter.enabled=true

# ============= ACTUATOR SETTINGS =============
management.endpoints.web.exposure.include=health,info,metrics,loggers,caches
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
info.app.name=Philharmonic Event Manager
info.app.description=Coursework project
info.app.version=1.0
info.app.java.version=@java.version@

spring.mvc.favicon.enabled=false