---- 1. Очистка таблиц (Spring Boot сделает это сам при create-drop)
--
---- 2. Добавление ролей (используем строки как в enum UserRoles)
--INSERT INTO roles (id, name, created_at, updated_at) VALUES
--('role_user', 'USER', NOW(), NOW()),
--('role_admin', 'ADMIN', NOW(), NOW());
--
---- 3. Добавление пользователей (с шифрованными паролями BCrypt)
---- Пароль для всех: 'password' = $2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iK6lFjLlhT7e2dO3h5W6Z5.8LJ6K
--INSERT INTO users (id, username, password, email, full_name, phone_number, birth_date, created_at, updated_at) VALUES
--('user1', 'ivanov', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iK6lFjLlhT7e2dO3h5W6Z5.8LJ6K', 'ivanov@mail.ru', 'Иванов Иван Иванович', '+79991112233', '1990-05-15', NOW(), NOW()),
--('user2', 'petrov', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iK6lFjLlhT7e2dO3h5W6Z5.8LJ6K', 'petrov@mail.ru', 'Петров Петр Петрович', '+79992223344', '1985-08-20', NOW(), NOW()),
--('user3', 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iK6lFjLlhT7e2dO3h5W6Z5.8LJ6K', 'admin@philharmonic.ru', 'Администратор Системы', '+79990000000', '1980-01-01', NOW(), NOW());
--
---- 4. Связь пользователей и ролей
--INSERT INTO users_roles (user_id, role_id) VALUES
--('user1', 'role_user'),  -- Иванов - USER
--('user2', 'role_user'),  -- Петров - USER
--('user3', 'role_admin'); -- admin - ADMIN
--
---- 5. Добавление залов
--INSERT INTO halls (id, name, address, capacity, created_at, updated_at) VALUES
--('hall1', 'Большой зал филармонии', 'ул. Ленина, 1, Москва', 1000, NOW(), NOW()),
--('hall2', 'Малый камерный зал', 'ул. Пушкина, 10, Москва', 300, NOW(), NOW()),
--('hall3', 'Органный зал', 'ул. Гагарина, 5, Москва', 500, NOW(), NOW()),
--('hall4', 'Зал имени Чайковского', 'ул. Музыкальная, 15, Москва', 800, NOW(), NOW());
--
---- 6. Добавление жанров
--INSERT INTO genres (id, name, created_at, updated_at) VALUES
--('genre1', 'Классическая музыка', NOW(), NOW()),
--('genre2', 'Джаз', NOW(), NOW()),
--('genre3', 'Рок', NOW(), NOW()),
--('genre4', 'Опера', NOW(), NOW()),
--('genre5', 'Балет', NOW(), NOW()),
--('genre6', 'Народная музыка', NOW(), NOW()),
--('genre7', 'Электронная музыка', NOW(), NOW());
--
---- 7. Добавление исполнителей
--INSERT INTO performers (id, name, description, genre_id, created_at, updated_at) VALUES
--('perf1', 'Московский симфонический оркестр', 'Один из старейших и наиболее известных симфонических оркестров России. Основан в 1951 году.', 'genre1', NOW(), NOW()),
--('perf2', 'Джаз-бэнд "Свинг"', 'Молодой, но уже известный джазовый коллектив, исполняющий как классические стандарты, так и собственные композиции.', 'genre2', NOW(), NOW()),
--('perf3', 'Группа "Рок-Волна"', 'Легендарная рок-группа, выступающая с 1990-х годов. Известна своими энергетичными концертами.', 'genre3', NOW(), NOW()),
--('perf4', 'Солистка Анна Петрова (сопрано)', 'Лауреат международных конкурсов, выпускница Московской консерватории.', 'genre4', NOW(), NOW()),
--('perf5', 'Балетная труппа "Грация"', 'Молодой, но уже получивший признание коллектив под руководством народного артиста России.', 'genre5', NOW(), NOW()),
--('perf6', 'Ансамбль народной музыки "Русские узоры"', 'Хранители традиций русской народной музыки.', 'genre6', NOW(), NOW()),
--('perf7', 'Ди-джей Alex Electro', 'Известный исполнитель электронной музыки, участник международных фестивалей.', 'genre7', NOW(), NOW());
--
---- 8. Добавление мероприятий
--INSERT INTO events (id, title, description, date_time, hall_id, available_seats, event_type, genre_id, image_url, created_at, updated_at) VALUES
--('event1', 'Вечер классической музыки', 'В программе: симфонии Бетховена, произведения Чайковского и Моцарта. Исполняет Московский симфонический оркестр под управлением маэстро Иванова.', '2024-12-15 19:00:00', 'hall1', 150, 'CONCERT', 'genre1', 'https://www.mos.ru/upload/newsfeed/newsfeed/GL(101577).jpg', NOW(), NOW()),
--('event2', 'Джазовая ночь', 'Лучшие джазовые стандарты в исполнении коллектива "Свинг". В программе произведения Луи Армстронга, Эллы Фицджеральд и современные аранжировки.', '2024-12-20 20:00:00', 'hall2', 50, 'CONCERT', 'genre2', 'https://www.tg-m.ru/img/news2020/emctol_09_10_01.jpg', NOW(), NOW()),
--('event3', 'Рок-фестиваль "Звуки весны"', 'Ежегодный фестиваль рок-музыки с участием лучших коллективов страны. Хэдлайнер: группа "Рок-Волна".', '2024-12-25 18:00:00', 'hall1', 200, 'FESTIVAL', 'genre3', 'https://www.interfax.ru/ftproot/textphotos/2023/06/02/en700.jpg', NOW(), NOW()),
--('event4', 'Опера "Евгений Онегин"', 'Постановка оперы П.И. Чайковского в 3 действиях. В главных партиях: Анна Петрова и приглашенные солисты Большого театра.', '2024-12-28 18:30:00', 'hall3', 120, 'THEATER', 'genre4', 'https://stanmus.ru/wp-content/uploads/2020/03/CHER3604-e1651934272807.jpg', NOW(), NOW()),
--('event5', 'Балет "Лебединое озеро"', 'Классическая постановка балета П.И. Чайковского в исполнении балетной труппы "Грация". Хореография Мариуса Петипа.', '2025-01-10 19:00:00', 'hall1', 80, 'THEATER', 'genre5', 'https://www.classicalmusicnews.ru/wp-content/uploads/2024/09/swan-lake.jpg', NOW(), NOW()),
--('event6', 'Лекция "История русской народной музыки"', 'Встреча с музыковедом и концерт ансамбля "Русские узоры". В программе: народные песни и инструментальная музыка.', '2025-01-15 17:00:00', 'hall2', 100, 'CINEMA', 'genre6', 'https://rgub.ru/img/news/47158-2.jpg?t=1761739262', NOW(), NOW()),
--('event7', 'Электронная вечеринка "Neon Nights"', 'Ночная вечеринка с лучшими диджеями. Хэдлайнер: Alex Electro. Light show, современное звуковое оборудование.', '2025-01-20 22:00:00', 'hall4', 250, 'CONCERT', 'genre7', 'https://media.istockphoto.com/id/1157545996/ru/%D1%84%D0%BE%D1%82%D0%BE/dj-%D0%B8%D0%B3%D1%80%D0%B0%D1%82%D1%8C-%D0%B8-%D1%81%D0%BC%D0%B5%D1%88%D0%B8%D0%B2%D0%B0%D1%82%D1%8C-%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D1%83-%D0%BD%D0%B0-%D0%B2%D0%B5%D1%87%D0%B5%D1%80%D0%B8%D0%BD%D0%BA%D0%B5.jpg?s=612x612&w=0&k=20&c=613Z_85w1RPN3CIIosWfsRkJWBTfB0AC5RmqbJwu0G4=', NOW(), NOW()),
--('event8', 'Мастер-класс по оперному вокалу', 'Для начинающих и профессиональных певцов. Проводит Анна Петрова. Разбор техники дыхания, постановки голоса, работа над репертуаром.', '2025-01-25 15:00:00', 'hall2', 30, 'MASTERCLASS', 'genre4', 'https://voicestudio.ru/wp-content/uploads/2020/10/discipliny-05-e1648054692140-1280x675.png', NOW(), NOW()),
--('event9', 'Концерт органной музыки', 'Произведения И.С. Баха, В.А. Моцарта, С. Франка в исполнении лауреата международных конкурсов.', '2025-02-05 19:30:00', 'hall3', 90, 'CONCERT', 'genre1', 'https://cdn.culture.ru/images/98631b1b-ff32-5ee6-ad1e-b648a6d75eae', NOW(), NOW()),
--('event10', 'Спектакль "Ревизор"', 'Современная интерпретация классической комедии Н.В. Гоголя. Молодой режиссер, нестандартный подход.', '2025-02-12 18:00:00', 'hall4', 180, 'THEATER', NULL, 'https://s1.afisha.ru/mediastorage/99/61/30360c73fc1944f8bfb29ecc6199.jpg', NOW(), NOW()),
--('event11', 'Спортивное шоу "Сила духа"', 'Зрелищное спортивное представление с участием чемпионов мира по гимнастике и акробатике.', '2025-02-20 19:00:00', 'hall1', 220, 'SPORT', NULL, 'https://s-cdn.sportbox.ru/images/styles/upload/fp_fotos/6a/a1/6ab815a126bd4128677d2383a1ae5b5d668644ba1d9b7123615716.jpg', NOW(), NOW()),
--('event12', 'Кинопоказ "Великие композиторы"', 'Документальный фильм о жизни и творчестве великих композиторов с обсуждением.', '2025-03-05 18:00:00', 'hall2', 120, 'CINEMA', 'genre1', 'https://mf.b37mrtl.ru/rbthmedia/images/2023.08/original/64ccc0a7fdff36569b4a4ca3.jpg', NOW(), NOW());
--
---- 9. Связь мероприятий и исполнителей
--INSERT INTO events_performers (event_id, performer_id) VALUES
--('event1', 'perf1'),
--('event2', 'perf2'),
--('event3', 'perf3'),
--('event4', 'perf4'),
--('event5', 'perf5'),
--('event6', 'perf6'),
--('event7', 'perf7'),
--('event8', 'perf4'),
--('event9', 'perf1'),
--('event10', 'perf1'),
--('event11', 'perf6'),
--('event12', 'perf1');